# Generated by Django 3.0.3 on 2020-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200224_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
