# Generated by Django 3.0.3 on 2020-02-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_quote_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
