# Generated by Django 3.0.3 on 2020-04-05 02:44

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='your name', max_length=20)),
                ('bio', models.TextField(blank=True, default='', help_text='about (( You ))')),
                ('avatar', models.ImageField(blank=True, help_text='your ugly face', upload_to=accounts.models.avatar_uploader)),
                ('favorite_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Quote')),
                ('following', models.ManyToManyField(blank=True, related_name='_account_following_+', to='accounts.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
