# Generated by Django 3.0.3 on 2020-03-03 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_auto_20200303_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='about (( You ))')),
                ('avatar', models.ImageField(help_text='your ugly face', upload_to='')),
                ('favorite_quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Quote')),
                ('following', models.ManyToManyField(related_name='_account_following_+', to='accounts.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
