# Generated by Django 3.0.3 on 2020-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200304_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, help_text='your ugly face', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, help_text='about (( You ))', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_account_following_+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, help_text='your name', max_length=20, null=True),
        ),
    ]
