# Generated by Django 3.0.3 on 2020-03-04 13:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200304_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', help_text='your ugly face', upload_to=accounts.models.avatar_uploader),
        ),
    ]
