# Generated by Django 3.0.3 on 2020-03-04 14:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200304_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/default_avatar.jpeg', help_text='your ugly face', upload_to=accounts.models.avatar_uploader),
        ),
    ]
