# Generated by Django 3.0.3 on 2020-03-03 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('about', models.TextField(max_length=400)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='quote',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Author'),
        ),
    ]
