# Generated by Django 3.0.3 on 2020-04-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200405_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='thumb',
            new_name='image',
        ),
    ]
