# Generated by Django 3.0.3 on 2020-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200405_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
