# Generated by Django 3.0.3 on 2020-04-08 20:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20200408_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
